### ISSUE TITLE
不兼容ASJCore

### ISSUE THREAD

**Issue by huihiuhuai** [Tesseract4D/Mycelium#4]
[fml-client-latest.log](https://github.com/user-attachments/files/17686314/fml-client-latest.log)

**Comment by Tesseract4D** [comment]
看样子不是这边的问题，去ASJ那边发issue看看

**Comment by huihiuhuai** [comment]
![Screenshot_2024-11-11-00-36-11-258_Discord](https://github.com/user-attachments/assets/68a9f0e4-eb3d-49e6-b8ab-a5cb365d26b1)

**Comment by huihiuhuai** [comment]
![Screenshot_2024-11-11-00-46-08-452_Discord](https://github.com/user-attachments/assets/811e2592-7fcd-4f7f-87d8-be2fcb8b87bd)
![image-30](https://github.com/user-attachments/assets/21235cfc-8321-442f-a8fc-fbb181df8c87)

**Comment by huihiuhuai** [comment]
![Screenshot_2024-11-11-00-52-46-776_Discord](https://github.com/user-attachments/assets/b678d300-2503-4d16-8bb9-6f5ae6ff86c4)

**Comment by AlexSocol** [comment]
Hey there o/
There is simplest fix - rename `methods.bin` to anything else.
