### ISSUE TITLE
why does mycelium make my game title say "Custom Title"??

### ISSUE THREAD

**Issue by brandyyn** [Tesseract4D/Mycelium#5]
there is no config for it, that's gross...

**Comment by Tesseract4D** [comment]
This is a debug function that I forgot to remove😅

**Comment by Tesseract4D** [comment]
I am preparing for a big update so it may be late

**Comment by brandyyn** [comment]
> This is a debug function that I forgot to remove😅

Or you can keep it and let us change the title in the config to whatever we want.
