### ISSUE TITLE
Crashes on server

### ISSUE THREAD

**Issue by CJCWIS** [Tesseract4D/Mycelium#6]
[crash-2024-12-12_12.19.51-server.txt](https://github.com/user-attachments/files/18115927/crash-2024-12-12_12.19.51-server.txt)
[fml-server-latest.log](https://github.com/user-attachments/files/18115928/fml-server-latest.log)

Crashes on server with almost no other mods present. It seems to try and load classes that only the client has?

**Comment by Tesseract4D** [comment]
Should be fixed in 2.0, update your worley's caves as well
