### ISSUE TITLE
Incompatibility between Mycelium and LWJGL3ify

### ISSUE THREAD

**Issue by CJCWIS** [Tesseract4D/Mycelium#7]
[fml-client-latest.log](https://github.com/user-attachments/files/18136881/fml-client-latest.log)
[fml-server-latest.log](https://github.com/user-attachments/files/18136882/fml-server-latest.log)

Crashes on both client and server, no crash report generated. Using Mycelium 2.0 and Worley's Caves 1.6, along with LWJGL3ify 2.1.5 (latest version of all mods at the time of writing)

Edit: should probably mention that I ran 1.5.11 on my client with LWJGL3ify and it worked flawlessly.

**Comment by Tesseract4D** [comment]
Try [this](https://modrinth.com/mod/myceliumlib/version/YY3E2JSs)

**Comment by Tesseract4D** [comment]
It was caused by new feature I just implemented.

**Comment by Tesseract4D** [comment]
By the way,what kind of server are you setting up?

**Comment by CJCWIS** [comment]
> By the way,what kind of server are you setting up?

Just a server for my friends and I. I never plan on publishing the modpack I made anywhere, outside of my friend group.
